INDIAN_BRAND_LEXICON = (
    "Aciloc",
    "Allegra",
    "Amlong",
    "Amlovas",
    "Amoxil",
    "Azee",
    "Becosules",
    "Becosules Z",
    "Becosules Plus",
    "Benadryl",
    "Betadine",
    "Calpol",
    "Cetcip",
    "Cetzine",
    "Chymoral",
    "Combiflam",
    "Corex",
    "Crocin",
    "Dolo",
    "Electral",
    "Enzoflam",
    "Ecosprin",
    "Evion",
    "Flagyl",
    "Gelusil",
    "Glycomet",
    "Glycomet GP",
    "Ibugesic",
    "Limcee",
    "Liv52",
    "Lopamide",
    "Montair",
    "Nicip",
    "Nise",
    "Norflox",
    "Omez",
    "Pacimol",
    "Pantocid",
    "Pan",
    "Rantac",
    "Razo",
    "Shelcal",
    "Sinarest",
    "Taxim",
    "Telma",
    "Teczine",
    "Uprise",
    "Voveran",
    "Volini",
    "Wikoryl",
    "Wysolone",
    "Zifi",
    "Zincovit",
)

