INDIAN_BRAND_LEXICON = (
    "Aciloc", "Allegra", "Amlong", "Amlovas", "Amoxil", "Azee",
    "Augmentin", "Azicip", "Azithral", "Aztor",
    "Becosules", "Benadryl", "Betadine", "Betaloc", "Betnesol",
    "Calpol", "Candid", "Ceftum", "Celin",
    "Cetcip", "Cetzine", "Cheston", "Chymoral",
    "Cifran", "Ciplox", "Clavam", "Clopitab",
    "Combiflam", "Corex", "Crocin", "Cyclopam",
    "Daflon", "Diclomol", "Digene",
    "Dolo", "Domstal", "Drotin", "Duolin",
    "Ecosprin", "Electral", "Eltroxin", "Emeset",
    "Eno", "Enzoflam", "Evion", "Exforge",
    "Febrex", "Flagyl", "Flexon",
    "Foracort", "Gaviscon", "Gelusil", "Glycomet",
    "Grilinctus", "Hifenac",
    "Ibugesic", "Imol", "Inderal",
    "Jalra", "Januvia",
    "Lariago", "Lasix", "Levolin", "Limcee",
    "Liv52", "Lobun", "Lopamide", "Losar",
    "Macbery", "Mahacef", "Maxtra", "Meftal",
    "Metformin", "Metrogyl",
    "Monocef", "Montair",
    "Moxikind", "Myospaz", "Naxdom", "Nebicard",
    "Nicip", "Nise", "Norflox",
    "Normaxin", "Novamox", "Nurokind",
    "Ocid", "Oflomac", "Okacet",
    "Omez", "Ondem", "Optineuron",
    "Pacimol", "Pan",
    "Pantocid", "Paracip", "Perinorm",
    "Phexin", "Piriton",
    "Prolomet", "Rablet",
    "Rantac", "Razo", "Relispray",
    "Revital", "Rifagut", "Rosuvas",
    "Shelcal", "Sinarest",
    "Sompraz", "Spasmonil", "Stemetil",
    "Sucral", "Sumo", "Susten",
    "Taxim", "Telma",
    "Teczine", "Thyronorm",
    "Tobradex", "Toradol", "Trika",
    "Uprise",
    "Veloz", "Vertin", "Voveran",
    "Volini", "Wikoryl", "Wysolone",
    "Xyzal", "Zedex", "Zerodol", "Zifi",
    "Zincovit", "Zithrocin", "Zoryl",
)

